### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by Timbar09** [Timbar09/RecipePlug#12]
Our team consists of two members.

Team member A - @Timbar09
Team member B - @Bestbynature

[Here](https://github.com/users/Timbar09/projects/4/views/1) is the link to the project.

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @Timbar09 and @Bestbynature,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### I cannot access your Kanban board. Kindly fix that. Maybe the link is broken?

![image](https://github.com/Timbar09/RecipePlug/assets/36542986/b67e64d4-ef77-462a-a370-b75375dc1c39)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Timbar09** [comment]
Sorry about that, @TedLivist. I didn't notice that. I fix it right away.

Thanks.

**Comment by prolajumokeoni** [comment]
Hi @Team

Your board setup is complete! 
Congratulations! 🎉 
## Highlights
 - Good setup   💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Timbar09** [comment]
Thanks, @prolajumokeoni. 🙃
